apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    jsonData:
      httpMethod: GET
      queryTimeout: 60s
      timeInterval: 15s
      keepCookies: []
      manageAlerts: false
      alertmanagerUid: ""
      exemplarTraceIdDestinations: []
      connectTimeout: 30
      timeout: 60
    secureJsonFields: {}
    withCredentials: false
